#!/usr/bin/env npx tsx
/**
 * Add a new song to K-pop Hangul app (Supabase direct insert).
 *
 * Usage:
 *   npx dotenv -e .env.local -- npx tsx scripts/newsong.ts add <json-file>
 *   npx dotenv -e .env.local -- npx tsx scripts/newsong.ts list
 *   npx dotenv -e .env.local -- npx tsx scripts/newsong.ts chart
 *
 * Commands:
 *   chart  - Fetch Billboard Korea Hot 100 & show songs not in DB
 *   list   - List all songs currently in DB
 *   add    - Add song from JSON file (generated by Claude Code)
 */

import { createClient } from "@supabase/supabase-js";
import { readFileSync } from "fs";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error("❌ Missing NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY");
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY, { db: { schema: "kh" } });

// ─── Theme color palette pool ───
const THEME_POOL = [
  { from: "from-rose-950", via: "via-pink-950", to: "to-black", accent: "text-rose-300", accentBg: "bg-rose-500", accentRing: "ring-rose-400", stickyFrom: "from-rose-950", stickyVia: "via-pink-950" },
  { from: "from-cyan-950", via: "via-teal-950", to: "to-black", accent: "text-cyan-300", accentBg: "bg-cyan-500", accentRing: "ring-cyan-400", stickyFrom: "from-cyan-950", stickyVia: "via-teal-950" },
  { from: "from-amber-950", via: "via-yellow-950", to: "to-black", accent: "text-amber-300", accentBg: "bg-amber-500", accentRing: "ring-amber-400", stickyFrom: "from-amber-950", stickyVia: "via-yellow-950" },
  { from: "from-fuchsia-950", via: "via-purple-950", to: "to-black", accent: "text-fuchsia-300", accentBg: "bg-fuchsia-500", accentRing: "ring-fuchsia-400", stickyFrom: "from-fuchsia-950", stickyVia: "via-purple-950" },
  { from: "from-lime-950", via: "via-green-950", to: "to-black", accent: "text-lime-300", accentBg: "bg-lime-500", accentRing: "ring-lime-400", stickyFrom: "from-lime-950", stickyVia: "via-green-950" },
  { from: "from-sky-950", via: "via-blue-950", to: "to-black", accent: "text-sky-300", accentBg: "bg-sky-500", accentRing: "ring-sky-400", stickyFrom: "from-sky-950", stickyVia: "via-blue-950" },
  { from: "from-pink-950", via: "via-rose-950", to: "to-black", accent: "text-pink-300", accentBg: "bg-pink-500", accentRing: "ring-pink-400", stickyFrom: "from-pink-950", stickyVia: "via-rose-950" },
  { from: "from-emerald-950", via: "via-teal-950", to: "to-black", accent: "text-emerald-300", accentBg: "bg-emerald-500", accentRing: "ring-emerald-400", stickyFrom: "from-emerald-950", stickyVia: "via-teal-950" },
  { from: "from-violet-950", via: "via-indigo-950", to: "to-black", accent: "text-violet-300", accentBg: "bg-violet-500", accentRing: "ring-violet-400", stickyFrom: "from-violet-950", stickyVia: "via-indigo-950" },
  { from: "from-orange-950", via: "via-red-950", to: "to-black", accent: "text-orange-300", accentBg: "bg-orange-500", accentRing: "ring-orange-400", stickyFrom: "from-orange-950", stickyVia: "via-red-950" },
];

// ─── Commands ───

async function listSongs() {
  const { data, error } = await supabase
    .from("songs")
    .select("id, title, artist, sort_order")
    .order("sort_order");

  if (error) {
    console.error("❌", error.message);
    return;
  }

  console.log(`\n📦 ${data.length} songs in database:\n`);
  data.forEach((s, i) => {
    console.log(`  ${i + 1}. ${s.artist} - ${s.title} (${s.id})`);
  });
  console.log();
}

async function fetchChart() {
  console.log("\n📊 Fetching Billboard Korea Hot 100...\n");

  try {
    const res = await fetch("https://www.billboard.co.kr/charts/billboard-korea-hot-100/");
    const html = await res.text();

    // Try to parse song entries from the HTML
    const songs: { rank: number; title: string; artist: string }[] = [];

    // Generic regex patterns for chart items
    const patterns = [
      // Pattern 1: numbered list items
      /(\d+)\s*[.)\]]\s*(.+?)\s*[-–—]\s*(.+?)(?:\n|$)/g,
      // Pattern 2: chart-specific classes
      /rank[^>]*>(\d+)<.*?title[^>]*>([^<]+)<.*?artist[^>]*>([^<]+)</gs,
    ];

    for (const pattern of patterns) {
      let match;
      while ((match = pattern.exec(html)) !== null) {
        songs.push({
          rank: parseInt(match[1]),
          title: match[2].trim().replace(/<[^>]*>/g, ""),
          artist: match[3].trim().replace(/<[^>]*>/g, ""),
        });
      }
      if (songs.length > 0) break;
    }

    if (songs.length === 0) {
      console.log("⚠️  Could not parse chart HTML automatically.");
      console.log("💡 Visit: https://www.billboard.co.kr/charts/billboard-korea-hot-100/");
      console.log("   Copy the chart and paste it to Claude Code to generate song JSON files.\n");
      return;
    }

    // Check which are new
    const { data: existing } = await supabase.from("songs").select("title, artist");
    const existingSet = new Set(
      (existing || []).map((s) => `${s.artist}|${s.title}`.toLowerCase())
    );

    const newSongs = songs.filter(
      (s) => !existingSet.has(`${s.artist}|${s.title}`.toLowerCase())
    );

    console.log(`Found ${songs.length} songs, ${newSongs.length} are new:\n`);
    newSongs.forEach((s) => {
      console.log(`  🆕 [${s.rank}위] ${s.artist} - ${s.title}`);
    });
    console.log(`\n💡 Ask Claude Code to generate JSON files for these songs, then run:`);
    console.log(`   npx dotenv -e .env.local -- npx tsx scripts/newsong.ts add <file.json>\n`);
  } catch (e) {
    console.error("❌ Failed to fetch chart:", (e as Error).message);
  }
}

async function addSong(jsonPath: string) {
  console.log(`\n📄 Reading ${jsonPath}...`);

  let songData: any;
  try {
    const raw = readFileSync(jsonPath, "utf-8");
    songData = JSON.parse(raw);
  } catch (e) {
    console.error("❌ Failed to read/parse JSON:", (e as Error).message);
    return;
  }

  const { id, title, artist, youtubeId, words } = songData;

  if (!id || !title || !artist || !youtubeId || !words?.length) {
    console.error("❌ JSON must have: id, title, artist, youtubeId, words[]");
    return;
  }

  // Get current song count for sort_order & theme
  const { count } = await supabase.from("songs").select("*", { count: "exact", head: true });
  const sortOrder = count || 0;
  const theme = songData.theme || THEME_POOL[sortOrder % THEME_POOL.length];

  // Upsert song
  const { error: songErr } = await supabase.from("songs").upsert({
    id,
    title,
    artist,
    youtube_id: youtubeId,
    theme,
    sort_order: sortOrder,
  });

  if (songErr) {
    console.error("❌ Song insert error:", songErr.message);
    return;
  }

  // Delete existing words & re-insert
  await supabase.from("words").delete().eq("song_id", id);

  const wordRows = words.map((w: any, i: number) => ({
    song_id: id,
    korean: w.korean,
    romanization: w.romanization,
    english: w.english,
    spanish: w.spanish || "",
    portuguese: w.portuguese || "",
    indonesian: w.indonesian || "",
    japanese: w.japanese || "",
    thai: w.thai || "",
    french: w.french || "",
    part_of_speech: w.partOfSpeech || w.part_of_speech || "",
    emoji: w.emoji || "",
    example: w.example || "",
    example_translation: w.exampleTranslation || w.example_translation || "",
    timestamp: w.timestamp ?? null,
    sort_order: i,
  }));

  const { error: wordsErr } = await supabase.from("words").insert(wordRows);
  if (wordsErr) {
    console.error("❌ Words insert error:", wordsErr.message);
    return;
  }

  console.log(`✅ Added: ${artist} - ${title} (${words.length} words)`);
  console.log(`   ID: ${id}`);
  console.log(`   YouTube: ${youtubeId}\n`);
}

// ─── Entry Point ───

const [cmd, ...args] = process.argv.slice(2);

switch (cmd) {
  case "list":
    listSongs();
    break;
  case "chart":
    fetchChart();
    break;
  case "add":
    if (!args[0]) {
      console.error("Usage: newsong add <song.json>");
      console.error("       newsong add songs/*.json  (multiple files)");
      process.exit(1);
    }
    (async () => {
      for (const file of args) {
        await addSong(file);
      }
    })();
    break;
  default:
    console.log(`
🎵 K-pop Hangul - newsong

Commands:
  list            List all songs in database
  chart           Fetch Billboard chart & show new songs
  add <file.json> Add song from JSON file

Workflow:
  1. Run 'chart' to see what's new
  2. Ask Claude Code to generate song JSON files
  3. Run 'add' to insert into Supabase

Examples:
  npx dotenv -e .env.local -- npx tsx scripts/newsong.ts list
  npx dotenv -e .env.local -- npx tsx scripts/newsong.ts chart
  npx dotenv -e .env.local -- npx tsx scripts/newsong.ts add songs/ive-bang-bang.json
  npx dotenv -e .env.local -- npx tsx scripts/newsong.ts add songs/*.json
`);
}
